[package]
name = "desktop"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "amphitheatre-desktop"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
amp-client = { git = "https://github.com/amphitheatre-app/amp-client-rust", tag="v0.6.0" }
amp-common = { git = "https://github.com/amphitheatre-app/common", tag="v0.6.0" }
iced = { version = "0.10.0", features = ["tokio", "debug"] }
iced_aw = { version = "0.7.0" }
rand = "0.8.5"
thiserror = "1.0"
time = { version = "0.3.5", features = ["local-offset"] }
