name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly-2022-12-01
    - uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo test --all --verbose

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly-2022-12-01
      with:
        components: rustfmt
    - name: Enforce formatting
      run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly-2022-12-01
      with:
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - name: Linting
      run: cargo clippy --all -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v3
    - name: Generate code coverage
      run: |
        cargo tarpaulin --verbose --workspace
